---
- name: install latest postgresql server
  apt: pkg=postgresql-{{postgresql_version}} state=installed

- name: check postgresql cluster created
  command: "/usr/bin/test -d /etc/postgresql"
  ignore_errors: True
  register: cluster_created
  changed_when: false

- name: create postgresql cluster if required
  when: cluster_created|failed
  shell: "LANG=en_US.UTF8
          LC_COLLATE=en_US.UTF8
          LC_CTYPE=en_US.UTF8
          LC_MESSAGES=en_US.UTF8
          LC_MONETARY=en_US.UTF8
          LC_NUMERIC=en_US.UTF8
          LC_TIME=en_US.UTF8
          LC_ALL=en_US.UTF8
          pg_createcluster {{postgresql_version}} main"

- name: check postgresql volume moved
  command: "/usr/bin/test -h /var/lib/postgresql"
  ignore_errors: True
  register: pg_moved
  changed_when: false

- name: move postgresql volume
  when: pg_moved|failed
  shell: "{{item}}"
  with_items:
    - /usr/sbin/service postgresql stop
    - mkdir -p {{postgresql_db_path}}
    - rmdir {{postgresql_db_path}}
    - mv /var/lib/postgresql {{postgresql_db_path}}
    - ln -s {{postgresql_db_path}} /var/lib/postgresql

- name: install PostgreSQL config file
  template: src=postgresql-{{postgresql_version}}.conf.j2
            dest=/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
            owner=postgres group=postgres
  notify:
    - restart postgresql

- name: install PostgreSQL hba file
  template: src=pg_hba-{{postgresql_version}}.conf
            dest=/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
            owner=postgres group=postgres
  notify:
    - restart postgresql

- name: enable daily cron for vacuum
  cron: name="daily vacuum" minute="0" hour="5"
        user="postgres"
        job="/usr/lib/postgresql/{{ postgresql_version }}/bin/vacuumdb -a -z"

#- name: enable weekly cron for full vacuum
#  cron: name="weekly vacuum full" minute="0" hour="6" weekday="0"
#        user="postgres"
#        job="/usr/lib/postgresql/{{ postgresql_version }}/bin/vacuumdb -a -z -f"
